#
# Makefile for cqrxs java
# 

# java runtime
# JAVA FLAGS for java runtime
JAVAFLAGS="--enable-native-access=ALL-UNNAMED" 
# JAVACFLAGS flags for javac compiler
JAVACFLAGS="-Xlint:unchecked -Xlint:deprecation"

# BCJAR=bcprov-jdk18on-1.79.jar
BCJAR=bcprov-lts8on-2.73.10.jar

# MYCLASSPATH local java classpath
MYCLASSPATH="$CLASSPATH:./:./$BCJAR:./eu/cqrxs/:./eu/cqrxs/gui/:./eu/cqrxs/fw/net/:./eu/cqrxs/fw/util/:./eu/cqrxs/fw/crypt/:./eu/cqrxs/fw/crypt/encoding/:./eu/cqrxs/fw/crypt/cipher/:./eu/cqrxs/fw/crypt/hash/:"

default: all

all: cqrxs

cqrxs:
    javac -classpath $(MYCLASSPATH) $(JAVACFLAGS) eu/cqrxs/fw/util/CException.java eu/cqrxs/fw/util/NotImplementedError.java eu/cqrxs/fw/util/Constants.java eu/cqrxs/fw/util/Fortune.java eu/cqrxs/fw/crypt/encoding/uu/CEFormatException.java eu/cqrxs/fw/crypt/encoding/uu/CEStreamExhausted.java eu/cqrxs/fw/crypt/encoding/uu/CharacterDecoder.java eu/cqrxs/fw/crypt/encoding/uu/CharacterEncoder.java  eu/cqrxs/fw/crypt/encoding/uu/UUDecoder.java  eu/cqrxs/fw/crypt/encoding/uu/UUEncoder.java eu/cqrxs/fw/crypt/encoding/EnDeCodeHelper.java eu/cqrxs/fw/crypt/encoding/EncodeEnum.java eu/cqrxs/fw/crypt/encoding/EnDeCoder.java  eu/cqrxs/fw/crypt/encoding/Base16Coder.java eu/cqrxs/fw/crypt/encoding/Hex16Coder.java eu/cqrxs/fw/crypt/encoding/Base64Coder.java  eu/cqrxs/fw/crypt/encoding/UuCoder.java 
	javac -classpath $(MYCLASSPATH) $(JAVACFLAGS) eu/cqrxs/fw/crypt/cipher/CipherEnum.java eu/cqrxs/fw/crypt/cipher/CipherPipe.java eu/cqrxs/fw/crypt/cipher/CryptBounceCastle.java eu/cqrxs/fw/crypt/cipher/CryptHelper.java eu/cqrxs/fw/crypt/cipher/CryptParams.java eu/cqrxs/fw/crypt/cipher/SymmCipherEnum.java 
	javac -classpath $(MYCLASSPATH) $(JAVACFLAGS) eu/cqrxs/fw/crypt/hash/Hex.java eu/cqrxs/fw/crypt/hash/KeyHash.java eu/cqrxs/fw/crypt/hash/OpenBSDCrypt.java eu/cqrxs/fw/crypt/hash/BCrypt.java eu/cqrxs/fw/crypt/hash/SCrypt.java  eu/cqrxs/fw/crypt/hash/MD5.java eu/cqrxs/fw/crypt/hash/RipeMD256.java eu/cqrxs/fw/crypt/hash/Sha1.java eu/cqrxs/fw/crypt/hash/Sha256.java eu/cqrxs/fw/crypt/hash/Sha384.java eu/cqrxs/fw/crypt/hash/Sha512.java eu/cqrxs/fw/crypt/hash/Whirlpool.java eu/cqrxs/fw/crypt/hash/Dstu7564.java
	javac -classpath $(MYCLASSPATH) $(JAVACFLAGS) eu/cqrxs/fw/util/CException.java eu/cqrxs/fw/util/Constants.java eu/cqrxs/fw/util/ContextLazy.java
	javac -classpath $(MYCLASSPATH) $(JAVACFLAGS) eu/cqrxs/fw/zip/GZ.java  eu/cqrxs/fw/zip/ZipType.java
	javac -classpath $(MYCLASSPATH) $(JAVACFLAGS) eu/cqrxs/gui/PropertyChangeSupport.java eu/cqrxs/gui/PropertyChangeSupport.java eu/cqrxs/fw/util/Fortune.java  eu/cqrxs/gui/ImageViewer.java eu/cqrxs/gui/CqrJDialog.java eu/cqrxs/gui/CqrJdFrame.java
	javac -classpath $(MYCLASSPATH) $(JAVACFLAGS) eu/cqrxs/gui/ImageTest.java
	echo "build finished"

run: cqrxs 
	echo "launching eu/cqrxs/gui/CqrJdFrame.java"
	sleep 1
	java $(JAVAFLAGS) -cp $(MYCLASSPATH) eu/cqrxs/gui/CqrJdFrame.java


# clean cleans client6 server6_clone 
clean: 
	echo "cleaning classes from last build in eu/cqrxs/ eu/cqrxs/cqrframe/ eu/cqrxs/gui/ "
	rm -rf *.class


