<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	<TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
	<UserSecretsId>aspnet-BlazorMicrosoftIdentity-437a817b-864a-4a76-9075-4e85b2e8ca61</UserSecretsId>
    <WebProject_DirectoryAccessLevelKey>0</WebProject_DirectoryAccessLevelKey>	
    <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <AssemblyTitle>EU.CqrXs.Web.BlazorMicrosoftIdentity</AssemblyTitle>
    <RepositoryUrl>https://github.com/heinrichelsigan/PermAgainCrypt</RepositoryUrl>
    <AssemblyVersion>2.23.515</AssemblyVersion>
    <FileVersion>2.23.515</FileVersion>
    <StartupObject>EU.CqrXs.Web.BlazorMicrosoftIdentity.Program</StartupObject>	    
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0" NoWarn="NU1605" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.0" NoWarn="NU1605" />
    <PackageReference Include="Microsoft.Identity.Web" Version="4.1.0" />
    <PackageReference Include="Microsoft.Identity.Web.UI" Version="4.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\EU.CqrXs.csproj" />
  </ItemGroup>

</Project>
